# Generated by Django 4.2.5 on 2024-12-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='address',
            field=models.CharField(default='No address provided', max_length=20),
        ),
    ]
